image: openjdk:15

variables:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  JACOCO_DOMAIN_CSV_LOCATION: '$CI_PROJECT_DIR/domain/build/jacocoCsv'
  JACOCO_DOMAIN_HTML_LOCATION: '$CI_PROJECT_DIR/domain/build/jacocoHtml'
  JACOCO_API_CSV_LOCATION: '$CI_PROJECT_DIR/api/build/jacocoCsv'
  JACOCO_API_HTML_LOCATION: '$CI_PROJECT_DIR/api/build/jacocoHtml'

stages:
  - build
  - test

build:
  stage: build
  script:
    - ./gradlew build

test:
  stage: test
  script:
    - ./gradlew test
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print "DOMAIN:"; print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' $JACOCO_DOMAIN_CSV_LOCATION
    - awk -F"," '{ instructions += $4 + $5; covered += $5 } END { print "API:"; print covered, "/", instructions, " instructions covered"; print 100*covered/instructions, "% covered" }' $JACOCO_API_CSV_LOCATION

test-frontend:
  stage: test
  image: node
  script: 
    - cd client
    - npm audit